---
- hosts: all
  user: ansadm
  become: yes
  gather_facts: yes
  tasks:
    - name: Add a line to a file if the file does not exist, without passing regexp
      lineinfile:
        path: /tmp/testfile1
        line: 'Today is beautiful'
        create: yes
