---
- hosts: all
  user: ansadm
  become: yes
  gather_facts: yes
  tasks:
    - name: Download maven binary 
      get_url:
        url: https://archive.apache.org/dist/maven/maven-4/4.0.0-alpha-10/binaries/apache-maven-4.0.0-alpha-10-bin.tar.gz
        dest: /tmp/
        mode: '755'
      tags:
        - download

    - name: Copy the binaries/apache-maven-4.0.0-alpha-10-bin.tar.gz into /opt dir
      copy:
        src: /tmp/apache-maven-4.0.0-alpha-10-bin.tar.gz
        dest: /opt/apache-maven-4.0.0-alpha-10-bin.tar.gz
        remote_src: yes
      tags:
        - copyingfiles

    - name: Unarchive a file that needs to be downloaded
      ansible.builtin.unarchive:
        src: /tmp/apache-maven-4.0.0-alpha-10-bin.tar.gz
        dest: /opt/
        remote_src: yes
      tags:
        - unarchiving
    
  
    - name: Add Maven environment variables to /etc/profile
      blockinfile:
        path: /etc/profile
        block: |
          # Maven environment variables
          M2_HOME=/opt/apache-maven-4.0.0-alpha-10
          export PATH=$PATH:$M2_HOME/bin

    - name: Notify user to refresh environment variables
      debug:
        msg: "Please run 'source /etc/profile' or log out and log back in to apply the environment changes."
