---
- hosts: all
  remote_user: ansadm
  become: yes
  gather_facts: yes
  tasks:
  - name: ensure nginx is at the latest version
    apt:
      name: nginx
      state: absent 
  - name: start nginx
    service:
      name: nginx
      state: started
