---
- hosts: all
  user: ansadm
  become: yes
  gather_facts: yes
  tasks:
    - name: Combination of loop and when condition
      command: echo "{{ item }}"
      with_items: [1,0,3,5,8,333,5342,23223]
      when: item > 5
      register: command_output  # Capture the output

    - name: Print full command output
      debug:
        var: command_output

